export const ProductData = [
  {
    id: 1,
    machine: "Goodway GLS",
    machineType: "CNC Torna",
    part: "Z:22 MN:2.5 WK:19.5",
    stock: "600.01.0216",
    opCode: "16.op-TRN",
    isPlanned: true,
    isActive: true,
    type: "Planned",
    category: "Planlanabilir Urunler",
    remainingWork: 999999,
    plannedQuantity: 120000,
    unplannedQuantity: 4500,
    activeTaskTime: "15:03",
  },
  {
    id: 2,
    machine: "CINCINNATI ARROW",
    machineType: "CNC Disli",
    part: "Z:22 MN:2.5 WK:19.5",
    stock: "600.01.0216",
    opCode: "16.op-TRN",
    isPlanned: true,
    isActive: true,
    type: "Planned",
    category: "Planlanabilir Urunler",
    remainingWork: 999999,
    plannedQuantity: 120000,
    unplannedQuantity: 4500,
    activeTaskTime: "15:03",
  },
  {
    id: 3,
    machine: "GLEASON PFAUTER",
    machineType: "Pasif Ekipmanlar",
    part: "Z:22 MN:2.5 WK:19.5",
    stock: "600.01.0216",
    opCode: "16.op-TRN",
    isPlanned: true,
    isActive: true,
    type: "Planned",
    category: "Planlanabilir Urunler",
    remainingWork: 999999,
    plannedQuantity: 120000,
    unplannedQuantity: 4500,
    activeTaskTime: "15:03",
  },
  {
    id: 4,
    machine: "Helis Disli Z:15 MN:6D",
    machineType: "CNC Disli",
    part: "Z:15 MN:6D",
    stock: "600.01.0216",
    opCode: "16.op-TRN",
    isPlanned: false,
    isActive: false,
    type: "Unplanned",
    category: "Esnek Urunler",
    remainingWork: 999999,
    plannedQuantity: 120000,
    unplannedQuantity: 3,
    activeTaskTime: null,
  },
  {
    id: 5,
    machine: "Helis Disli Z:15 MN:6D",
    machineType: "CNC Disli",
    part: "Z:15 MN:6D",
    stock: "600.01.0216",
    opCode: "16.op-TRN",
    isPlanned: false,
    isActive: true,
    type: "Unplanned",
    category: "Planlanabilir Urunler",
    remainingWork: 999999,
    plannedQuantity: 120000,
    unplannedQuantity: 3,
    activeTaskTime: "15:03",
  },
  {
    id: 6,
    machine: "DMG MORI NLX2500",
    machineType: "CNC Torna",
    part: "Z:18 MN:3.0 WK:16.2",
    stock: "600.01.0218",
    opCode: "18.op-TRN",
    isPlanned: true,
    isActive: true,
    type: "Planned",
    category: "Planlanabilir Urunler",
    remainingWork: 850000,
    plannedQuantity: 95000,
    unplannedQuantity: 3800,
    activeTaskTime: "16:30",
  },
  {
    id: 10,
    machine: "Helis Disli Z:15 MN:6D",
    machineType: "CNC Disli",
    part: "Z:15 MN:6D",
    stock: "600.01.0216",
    opCode: "16.op-TRN",
    isPlanned: false,
    isActive: true,
    type: "Unplanned",
    category: "Planlanabilir Urunler",
    remainingWork: 999999,
    plannedQuantity: 120000,
    unplannedQuantity: 3,
    activeTaskTime: "15:03",
  },
  {
    id: 12,
    machine: "DOOSAN PUMA",
    machineType: "CNC Torna",
    part: "Z:30 MN:2.2 WK:28.0",
    stock: "600.01.0230",
    opCode: "28.op-TRN",
    isPlanned: true,
    isActive: true,
    type: "Planned",
    category: "Planlanabilir Urunler",
    remainingWork: 1150000,
    plannedQuantity: 135000,
    unplannedQuantity: 6500,
    activeTaskTime: "11:45",
  },
];
